spring:
  application:
    name: SUBMISSION-SERVICE

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT}

user-service:
  host: ${HOST}
  port: ${USER_PORT}
  url: http://${user-service.host}:${user-service.port}

task-service:
  host: ${HOST}
  port: ${TASK_PORT}
  url: http://${task-service.host}:${task-service.port}

logging:
  level:
#    org.springframework.web: DEBUG
    org.springframework.security : DEBUG

resilience4j:
  circuitbreaker:
    instances:
      taskService:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 60
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true

  retry:
    instances:
      taskService:
        max-attempts: 3
        wait-duration: 1s

eureka:
  host: ${HOST}
  port: ${EUREKA_PORT}

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}


  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.host}:${eureka.port}/eureka/
